export const Actions = {
    SET_ENTRY: 'SET_ENTRY',
    SET_TITLE: 'SET_TITLE',
    SET_DESCIPTION: 'SET_DESCIPTION',
    SET_DATE: 'SET_DATE',
    SET_END_DATE: 'SET_END_DATE',
    TOGGLE_COMPLETED: 'TOGGLE_COMPLETED',
    CLEAR_INPUT: 'CLEAR_INPUT',
    INITIAL_STATE: 'INITIAL_STATE'
};